name: 逸轩的GitHub  the github website of yixuan
url: https://xiaohang007.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: 我 me
  - key: grad
    name: 我的小伙伴 my friends
  - key: ugrad
    name: 阿吧阿吧
  - key: collab
    name: 我的老师们 my teachers


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 课堂学习成果 Research
    link: /research.html
  - title: 老师的论文 Publications
    link: /publications.html
